name: Release ZIP on tag
on:
  push:
    tags: ["v*"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make plugin zip
        run: |
          PLUG="$(basename $GITHUB_WORKSPACE)"
          mkdir -p artifact
          zip -r "artifact/${PLUG}.zip" . \
            -x ".git/*" "node_modules/*" "vendor/*" ".github/*" "*.DS_Store" "tests/*" "coverage/*"
      - uses: softprops/action-gh-release@v2
        with:
          files: artifact/*.zip
