name: secret-tripwire
on: [pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if .env-like files are present
        run: |
          set -e
          if git ls-files | grep -E '(^|/)\.env(\.local|\.sample|\.example)?$'; then
            echo "::error:: .env-like file detected in repo. Remove and re-push."
            exit 1
          fi
          echo "OK"